name: Compile KSU Kernel

on:
  push:
    branches: [ "**" ] # This forces it to run no matter what branch you are on
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v4

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            bc bison build-essential ccache curl flex git libelf-dev libncurses5-dev \
            libssl-dev python3 perl rsync xz-utils zlib1g-dev \
            binutils-aarch64-linux-gnu binutils-arm-linux-gnueabi \
            gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi

      - name: Download Proton Clang
        run: |
          git clone --depth=1 https://github.com/kdrag0n/proton-clang.git $GITHUB_WORKSPACE/proton-clang

      - name: Compile the Kernel
        run: |
          export PATH="$GITHUB_WORKSPACE/proton-clang/bin:$PATH"
          export ARCH=arm64
          export SUBARCH=arm64
          make O=out enchilada_defconfig
          make O=out prepare headers_install
          make -j$(nproc --all) O=out \
            CC=clang \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
            CLANG_TRIPLE=aarch64-linux-gnu-

      - name: Upload Compiled Kernel
        uses: actions/upload-artifact@v4
        with:
          name: OnePlus6-KSU-Image
          path: out/arch/arm64/boot/Image.gz-dtb
